version: "3.7"

x-service-volumes: &service-volumes
    - ./:/usr/src/app/:rw,cached

x-database-variables: &database-variables
    POSTGRES_DB: carbonator
    POSTGRES_USER: carbonator
    POSTGRES_PASSWORD: carbonator

x-app-variables: &app-variables
    <<: *database-variables
    POSTGRES_HOST: postgres    

services:
    website:
        build: ./docker/website
        image: carbonator:latest
        container_name: django_image
        # line below prevents website image exiting before tests are run
        command: >
            bash -c "
            until PGPASSWORD="carbonator" psql -h "postgres" -U "carbonator" -c '\q';
            do sleep 1;
            done && 
            tail -f /dev/null"
        volumes: *service-volumes
        environment: *app-variables
        ports:
            - "8000:8000"
        
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        container_name: postgres_image
        ports:
            - "5432:5432"
        environment: *database-variables
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
    