version: "3.7"

x-service-volumes: &service-volumes
    - ./:/usr/src/app/:rw,cached

x-database-variables: &database-variables
    POSTGRES_DB: carbonator
    POSTGRES_USER: carbonator
    POSTGRES_PASSWORD: carbonator

x-app-variables: &app-variables
    <<: *database-variables
    POSTGRES_HOST: postgres    

services:

    postgres:
        image: postgres:latest
        container_name: postgres_image
        environment: *database-variables

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

        volumes:
            - db-data:/var/lib/postgresql/data

    website:    
        build: ./docker/website
        image: carbonator:latest
        container_name: django_image
        
        
        # prevent website image exiting before tests are run
        command: tail -f /dev/null

        volumes: *service-volumes
        environment: *app-variables
        
        depends_on:
            postgres:
                condition: service_healthy
volumes:
    db-data:
    