FROM python:3

ARG APP_HOME

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED=1

WORKDIR ${APP_HOME}/

RUN apt-get update && \
    apt-get install -y \
    postgresql-client \
    chromium \
    libpcre3 \
    libpcre3-dev \
    python-dev

COPY . .

RUN pip install -r docker/website/requirements.txt
