version: "3.9"

x-database-variables: &database-variables
    POSTGRES_DB: carbonator
    POSTGRES_USER: carbonator
    POSTGRES_PASSWORD: carbonator

x-app-variables: &app-variables
    <<: *database-variables
    POSTGRES_HOST: postgres    

services:
    website:
        build:
            dockerfile: ./docker/website/Dockerfile
            context: .        
        image: carbonator:latest
        container_name: django_image
        command: >
            bash -c "
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            uwsgi capstone.ini
            "
        volumes:
            - static-volume:/usr/src/app/static

        environment: *app-variables
        
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        build: ./docker/postgres
        image: postgres:latest
        container_name: postgres_image
        environment: *database-variables

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U carbonator"]
            interval: 10s
            timeout: 5s
            retries: 5

        volumes:
            - db-data:/var/lib/postgresql/data

    nginx:
        build: ./docker/nginx
        container_name: nginx_image
        restart: always

        volumes:
            - static-volume:/usr/src/app/static
            
        ports:
            - 8080:80
        depends_on:
                - website

volumes:
    db-data:
    static-volume: