version: "3.7"

x-service-volumes: &service-volumes
    - ./:/usr/src/app/:rw,cached

x-database-variables: &database-variables
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

x-app-variables: &app-variables
    <<: *database-variables
    POSTGRES_HOST: postgres
    SECRET_KEY: ${SECRET_KEY}

services:
    website:
        build: ./docker/website
        # image: carbonator:latest
        container_name: django_image
        command: >
            bash -c "
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            uwsgi capstone.ini
            "
        # volumes: *service-volumes
        volumes:
            - ./:/usr/src/app/:rw,cached
            - static-volume:/usr/src/app/static

        environment: *app-variables
        # expose:
        #    - 8080
        
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:latest
        container_name: postgres_image
        environment: *database-variables

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U carbonator"]
            interval: 10s
            timeout: 5s
            retries: 5

        volumes:
            - db-data:/var/lib/postgresql/data

    nginx:
        build: ./docker/nginx
        container_name: nginx_image
        restart: always

        volumes:
            - static-volume:/usr/src/app/static
            - ${PWD}/docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
            
        ports:
            - 8080:80
        depends_on:
                - website

volumes:
    db-data:
    static-volume: