# Generated by Django 3.1.6 on 2021-04-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('watts', models.DecimalField(decimal_places=2, max_digits=6)),
                ('typicalDuration', models.IntegerField()),
            ],
        ),
    ]
