# Generated by Django 3.1.6 on 2021-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='deleteFlag',
            field=models.BooleanField(default=False),
        ),
    ]
