# Generated by Django 3.1.6 on 2021-05-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbonator', '0002_saving_deleteflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=6)),
                ('moneyUnit', models.CharField(max_length=16)),
                ('co2e', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trees', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
