# Generated by Django 3.1.6 on 2021-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonator', '0003_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='money',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
