# Generated by Django 3.1.6 on 2021-05-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbonator', '0005_auto_20210504_1117'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
