name: Testing Carbonator App
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django Tests
      run: |
        sudo apt install chromium-browser
        pip3 install --user django
        pip3 install --user selenium
        python3 manage.py test
