name: Testing Carbonator in Docker Containers
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose  -f docker-compose-ci.yml up -d
    - name: Run test suite
      run: docker exec django_image python manage.py test