name: Testing Master
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: carbonator
          POSTGRES_PASSWORD: carbonator
          POSTGRES_DB: carbonator
        volumes:
          - postgres_data:/var/lib/postgresql/12/main
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Run Django Tests
      run: |
        # sudo apt-get install postgresql postgresql-contrib
        # sudo apt-get install postgresql-client
        sudo apt-get install libpq-dev
        sudo apt-get install chromium-browser
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        # pip3 install --user psycopg2
        # pip3 install --user django
        # pip3 install --user selenium
        python3 manage.py test
