name: Testing Carbonator App
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django Tests
      run: |
        sudo apt-get install postgresql postgresql-contrib
        # sudo apt-get install postgresql-client
        # sudo apt-get install libpq-dev
        sudo apt-get install chromium-browser
        pip3 install --user psycopg2
        pip3 install --user django
        pip3 install --user selenium
        python3 manage.py test
